version: '3.6'
services:
  app:
    build: .
    ports:
      - 8081:8081
      - 8082:8082
    environment:
      MONGODB_HOST: mongo
      REDIS_HOST: redis
      KAFKA_HOST: kafka
      RABBIT_HOST: rabbit
    depends_on:
      - redis
      - kafka
      - rabbit
      - mongo
    networks:
      - backend-crud
    labels:
      kompose.service.type: loadbalancer

  psql:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 213123
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    networks:
      - backend-crud

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka
    networks:
      - backend-crud
    labels:
      kompose.service.type: loadbalancer

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend-crud
    labels:
      kompose.service.type: clusterip

networks:
  backend-crud:
    name: backend-crud
    driver: bridge
