### get all users
GET http://localhost:8080/api/user/list
Accept: application/json

### get user by id
GET http://localhost:8080/api/user/5e3574be77a8167a646a9eb7
Accept: application/json

### create user
PUT http://localhost:8080/api/user
Content-Type: application/json

{ "name": "zzz2222123123asd2", "surname": "Targarian" }

### update user
POST http://localhost:8080/api/user
Content-Type: application/json

{ "id": "5e36d3bf5d60366431a57161", "name": "Tirion", "surname": "Lanister" }


### delete user
DELETE http://localhost:8080/api/user
Content-Type: application/json

{ "id": "5e36d3bf5d60366431a57161" }

###

