apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    org.backend.crud: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      org.backend.crud: kafka
  template:
    metadata:
      labels:
        org.backend.crud: kafka
    spec:
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        image: bitnami/kafka:latest
        name: kafka
        ports:
        - containerPort: 9092
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    org.backend.crud: kafka
  type: ClusterIP
