apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    org.backend.crud: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      org.backend.crud: redis
  template:
    metadata:
      labels:
        org.backend.crud: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    org.backend.crud: redis
  type: ClusterIP
