apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    org.backend.crud: app
spec:
  replicas: 1
  selector:
    matchLabels:
      org.backend.crud: app
  template:
    metadata:
      labels:
        org.backend.crud: app
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: {{ .Values.kafka.host }}
        - name: KAFKA_PORT
          value: "{{ .Values.kafka.port }}"
        - name: MONGODB_HOST
          value: {{ .Values.mongo.host }}
        - name: MONGODB_PORT
          value: "{{ .Values.mongo.port }}"
        - name: RABBIT_HOST
          value: {{ .Values.rabbit.host }}
        - name: RABBIT_PORT
          value: "{{ .Values.rabbit.port.server }}"
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        image: app
        imagePullPolicy: Never
        name: app
        ports:
        - containerPort: {{ .Values.app.ktor.port }}
        - containerPort: {{ .Values.app.spring.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: ktor
      port: {{ .Values.app.ktor.port }}
    - name: spring
      port: {{ .Values.app.spring.port }}
  selector:
    org.backend.crud: app
  type: LoadBalancer
