apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    org.backend.crud: kafka
spec:
  serviceName: kafka
  replicas: 2
  selector:
    matchLabels:
      org.backend.crud: kafka
  template:
    metadata:
      labels:
        org.backend.crud: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.zookeeper.host }}:{{ .Values.zookeeper.port }}"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        image: bitnami/kafka:latest
        name: kafka
        ports:
        - containerPort: {{ .Values.kafka.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: {{ .Values.kafka.port }}
  selector:
    org.backend.crud: kafka
